server:
  port: 8080
  max-http-header-size: 10000000
spring:
  application:
    name: AndroidDungeon
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
    generate-ddl: true
  jax:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/DB_AndroidsDungeon
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
  security:
    user:
      name: spring-admin
      password: sadmin
      roles: ADMIN
